[project]
name = "restaurant-name-generater"
version = "0.1.0"
description = "Generate creative restaurant names based on cuisine type using LLM."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
